apiVersion: v1
kind: Secret
metadata:
  name: shankistea-secret
type: Opaque
data:
  MYSQL_PASSWORD: S2lubmlnb2xpMTYyMQ==
  SECRET_KEY: Y2Y3MjA0MTQwOTFiYmViNzFmNzU1OWVkZWRjNGRjZDVhMWMzYTk1MWQ4MzdlOTE0MzI4ZjczYWMxM2YzNzg3YQ==
